<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="DESKTOP-VHHGVR3" name="org.testng1.Sample1" tests="8" failures="1" timestamp="21 Feb 2021 05:40:36 GMT" time="0.050" errors="0">
  <testcase name="tc1" time="0.003" classname="org.testng1.Sample1"/>
  <testcase name="tc0" time="0.016" classname="org.testng1.Sample1"/>
  <testcase name="tc2" time="0.002" classname="org.testng1.Sample1">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at org.testng1.Sample1.tc2(Sample1.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.007" classname="org.testng1.Sample1">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.002" classname="org.testng1.Sample1">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.008" classname="org.testng1.Sample1">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.008" classname="org.testng1.Sample1">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.004" classname="org.testng1.Sample1">
    <skipped/>
  </testcase> <!-- tc2 -->
</testsuite> <!-- org.testng1.Sample1 -->
